desc 'install all'
task :default => ['vim-vundle', 'tmux-tpm', 'atom-pkgs']

desc 'install vim-vundle'
task 'vim-vundle' do
  target = './.vim/bundle/Vundle.vim'
  if File.exist?(target)
    puts "#{target} alredy exists"
  else
    sh "git clone https://github.com/VundleVim/Vundle.vim.git #{target}"
    puts 'Launch vim and run :PluginInstall'
  end
end

desc 'install Tmux Plugin Manager'
task 'tmux-tpm' do
  target = './.tmux/plugins/tpm'
  if File.exist?(target)
    puts "#{target} alredy exists"
  else
    sh "git clone https://github.com/tmux-plugins/tpm #{target}"
  end
end

desc 'install atom packages'
task 'atom-pkgs' do
  require 'yaml'
  pkgs = YAML.load(File.read('./.atom/packages.yml')).values.flatten
  sh "apm install #{pkgs.join(' ')}"
end
